### PR TITLE
Fedora upstream changes

### PR DESCRIPTION
**Pull request by orpiske**
@icraggs, based on our conversation, I am requesting the Eclipse Paho C project inclusion in the Fedora distribution. I would, kindly, request to leave this PR open until the project is officially included in Fedora, because they may request additional changes on packaging.

### CODE REVIEW

**Comment by orpiske** [comment]
Fedora inclusion request link: https://bugzilla.redhat.com/show_bug.cgi?id=1476458

**Comment by icraggs** [comment]
Thank you.  I think I'd prefer to open an issue for the Fedora submission as it could result in a number of pull requests and other discussion.  What do you think?

**Comment by icraggs** [comment]
The PR is automatically closed on merge.  I've opened issue #315 to track the Fedora submission.

**Comment by rashed043** [comment]
Hello,
I am quite new about MQTT. I need to implement this protocol in vxwork. I try to read through theory of MQTT and have understand. As i want to implement with vxWork, i found this is a very much useful source of code. But it is little bit difficult for understand the starting point.  Could you please send or write a small docs so that i can understand the project. as i told before i am new with MQTT and vxWork so if i write some thing mistakenly please consider that.

**Comment by orpiske** [comment]
Hello @rashed043, 

I would recommend you to write to the Paho C mailing list. You are more likely to receive support there. This page here is related to a contribution made to the Paho project. You can find details about the Paho mailing lists here: https://dev.eclipse.org/mailman/listinfo/paho-dev. 

Good luck!

**Pull request merged**
