### PR TITLE
373

### PR DESCRIPTION
**Pull request by JuergenKosel**
This pull request allows to use the functions declared in Heap.h in C++ code to track memory usage by this library.
And it removes an unused function.

### CODE REVIEW

**Comment by JuergenKosel** [comment]
With the added test I could also reproduce the segmentation fault, if running with enough iterations:
```
20171206 145029.773 PublishCnt 5208766, FailedCnt 105, Pending 131193 maxPending 162849
20171206 145029.773 MQTT mem current 29387120, max 36480624
20171206 145029.787 Established MQTT connection to SLGB-VM-MQTTSRV.inat.internal:1883
20171206 145029.787   MQTT version 3.1.1

20171206 145029.787 connectCnt 71
[197124.728360] test_issue373[4386]: segfault at 0 ip 00007f14eceb0071 sp 00007f14ec6d1e00 error 4 in libpaho-mqtt3a.so.1.2.0[7f14ece93000+24000]
```

**Comment by JuergenKosel** [comment]
Commit b4bdb89861bb72537b8aa564db2d56b311b96803 sets pointers to just freed memory to NULL.
And now a unit test fails. - Strange!
Maybe it is worth to take a second look, regarding issue #385

**Comment by JuergenKosel** [comment]
It looks like one of our changes has broken something related to publish with QoS=1:
The connection lost call back is not called, with many outstanding QoS=1 messages in the send queue.

I will modify the test_issue373 to test with all 3 kinds of QoS.

**Comment by JuergenKosel** [comment]
After extending the test, I see that we now have a memory leak for QoS=1:
First test result with QoS=0:
```
20171208 150044.417 connectCnt 5

20171208 150052.394 PublishCnt 17800, FailedCnt 0, Pending 1 maxPending 1001
20171208 150052.394 MQTT mem current 1296, max 225488
20171208 150052.394 PublishCnt 17800, FailedCnt 0, Pending 1 maxPending 1001
20171208 150052.394 MQTT mem current 1440, max 225488
20171208 150052.895 MQTT mem current 0, max 225488
```
And test result with QoS=1:
```
20171208 151038.142 connectCnt 5

20171208 151046.006 PublishCnt 79263, FailedCnt 2, Pending 1 maxPending 25561
20171208 151046.006 MQTT mem current 1344, max 10597568
20171208 151046.006 PublishCnt 79263, FailedCnt 2, Pending 1 maxPending 25561
20171208 151046.006 MQTT mem current 1488, max 10597568
20171208 151046.982 Some memory not freed at shutdown, possible memory leak
20171208 151046.982 Heap scan start, total 48 bytes
20171208 151046.982 Heap element size 16, line 696, file /home/klj/org.eclipse.paho.mqtt.c/src/MQTTPacket.c, ptr 0x7faa30001b50
20171208 151046.982   Content           
20171208 151047.006 Heap element size 16, line 704, file /home/klj/org.eclipse.paho.mqtt.c/src/MQTTPacket.c, ptr 0x7faa30003360
20171208 151047.006   Content           
20171208 151047.006 Heap element size 16, line 231, file /home/klj/org.eclipse.paho.mqtt.c/src/MQTTPacket.c, ptr 0x7faa30299bf0
20171208 151047.006   Content           
20171208 151047.006 Heap scan end
20171208 151047.027 MQTT mem current 48, max 10597568
```

**Comment by JuergenKosel** [comment]
Hello @icraggs 

I have run my tests with the commits of this pr included.
Are you sure, that the fix in 779ca42a46afd3c80bd90a2bac68c8412b0dfc4b is not needed?

**Comment by icraggs** [comment]
This PR was automatically closed apparently when I merged the 373 branch into develop - I didn't do it myself.  The commit you point out may well be needed - I haven't encountered the problem it is intended to fix myself (as I have the others), but I will probably merge that or something similar soon.

**Pull request closed without merging**
