### PR TITLE
Fix MSVC build errors with Visual Studio 2010

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by icraggs** [comment]
What build errors does this fix?  I don't think I see any in WebSocket.c 

https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/build/1.2.443/job/svr2tjwlk1i4ph48?fullLog=true

Also is the macro definition for htonll(x) copied from somewhere?

**Comment by tbeu** [comment]
It is for VS 2010 with enabled ssl support. Not sure if you want to drop VS 2010 support with v1.3.0.

htonll/ntohll is not available with VS 2010. Yes, macros were copied from some other source: https://github.com/biochem-fan/eiger2cbf/blob/master/lz4/h5zlz4.c#L24-L25 (BSD). www.cs.columbia.edu/~zwb/project/dotslash/dots_apache/util.c is somewhat shorter (and also BSD).

**Comment by icraggs** [comment]
I don't mind continuing support for VS 2010, but I'll have to remind myself of the policy of copying code from elsewhere.  It'll probably need review.

**Comment by tbeu** [comment]
Let me think about the copied code if I can get it from public domain.

**Comment by tbeu** [comment]
Shorter and cleaner and tested to build in VS2010 and VS2015 (but not tested in MinGW or CygWin).

**Comment by icraggs** [comment]
Ok, I see you've used MS functions now instead of the macros.  That's great.  Unfortunately the last commit is missing the 'signed-off-by' footer - the other two commits have it.  I can merge the changes if that is fixed.

**Comment by tbeu** [comment]
OK, I rebased and checked it all again (this time also MQTTAsync.c where there have been some issues in MQTTAsync_randomJitter).

Additional remarks:
* This PR replaces #560 and #561, which should be closed without merge then.
* This PR only works together with #529, which I still have open as separate PR.

**Comment by tbeu** [comment]
And again, I rebased the three commits, resolved the merge conflicts and checked again in VS2010 that paho-mqtt3a, paho-mqtt3as, paho-mqtt3c and paho-mqtt3cs build.

Correction: This PR is independent of #529 (which fixes the remaining warnings).

**Comment by icraggs** [comment]
Merged into the develop branch.  Thanks.

**Pull request closed without merging**
