### PR TITLE
add missing OPENSSL define to CMakeLists.txt

### PR DESCRIPTION
**Pull request by rpendleton**
It looks like at some point, the cc flag for `OPENSSL=1` was lost. Because of this, OpenSSL versions of the MQTT library don't actually include SSL support. This caused some weird issues such as attempting to resolve hostnames with the `ssl://` prefix and SSL not actually being used, despite compiling without any issues.

### CODE REVIEW

**Comment by prateekbansal** [comment]
@rpendleton the code seems to have changed since my last pull request (around a couple of weeks back) which had that issue. Possibly the issue got resolved because I don't see that code anymore.

**Comment by JuergenKosel** [comment]
Hello,
the issue is still there. I just trapped in while building for windows target with cmake and visual studio 2010. (That's why I have to use cmake instead of the existing .sln files.)

**Comment by rpendleton** [comment]
@JuergenKosel You're correct, as the problem is still there. When @prateekbansal said the issue was potentially resolved in later changes, he was referring to issue #144 rather than this one.

**Comment by JuergenKosel** [comment]
For visual studio 2010 I need to define WIN32_LEAN_AND_MEAN, if the macro OPENSSL is defined.
Otherwise compilation fails in src/StackTrace.c due to inconsistant/duplicate type definitions.
Maybe this macro should also be added to the cmake file.

**Comment by BeLearner** [comment]
problem still exists.Please fix it.I spent a whole afternoon to figure out why I couldn't connect with SSL.It turns out to be a problem of the repository.So Please fix it as soon as possible

**Comment by rpendleton** [comment]
@BeLearner Did you still experience problems after applying the changes from this pull request?

**Comment by BeLearner** [comment]
@rpendleton No,I haven't apply the changes from this pull request.Let me have a try.

**Comment by BeLearner** [comment]
I build again with *COMPILE_DEFINITIONS "OPENSSL=1"*.It works now.Thanks @rpendleton .Please merge this pull request to master as soon as possilbe so that others won't get confused.

**Comment by icraggs** [comment]
Thanks for fixing this.

**Pull request merged**
