### PR TITLE
Initializing static library on Windows

### PR DESCRIPTION
**Pull request by uhuntu**
Thank you for your interest in this project managed by the Eclipse Foundation.

The guidelines for contributions can be found in the CONTRIBUTING.md file.

At a minimum, you must sign the Eclipse ECA, and sign off each commit.  

To complete and submit a ECA, log into the Eclipse projects forge 
You will need to create an account with the Eclipse Foundation if you have not already done so.
Be sure to use the same email address when you register for the account that you intend to use when you commit to Git.
Go to https://accounts.eclipse.org/user/eca to sign the Eclipse ECA.

### CODE REVIEW

**Comment by icraggs** [comment]
I'm not sure what problem you're trying to solve here?

**Comment by uhuntu** [comment]
> I'm not sure what problem you're trying to solve here?

When I am trying to use statically build on windows, I met the trouble.

**Comment by jumoog** [comment]
i guess its related to #565 
https://github.com/eclipse/paho.mqtt.c/issues/565#issuecomment-463221351

**Review by icraggs — CHANGES_REQUESTED** [review]
Ok.  There are two problems with this:

1) the code is duplicated from DllMain - if it's going to be reused it should be put into a function and then called from wherever it's needed.

2) By the time we get to connect(), mutexes have already been used - it's too late.  Create() or global_init is where initialization is currently done.  The create() call also uses a mutex at the top, so that won't work either, leaving two options: 
a) a static initialization (which may have to be conditional on a static build)
b) in global_init() which will then have to be called when using the library statically.  
Using global_init() will provide most control to the application, I think.

**Comment by icraggs** [comment]
Ok, this is fixed in PR #341, which I've now merged into the develop branch.  Thanks.

**Pull request closed without merging**
