### PR TITLE
Fix issue #676

### PR DESCRIPTION
**Pull request by michalkas**
Thank you for your interest in this project managed by the Eclipse Foundation.

The guidelines for contributions can be found in the CONTRIBUTING.md file.

At a minimum, you must sign the Eclipse ECA, and sign off each commit.  

To complete and submit a ECA, log into the Eclipse projects forge 
You will need to create an account with the Eclipse Foundation if you have not already done so.
Be sure to use the same email address when you register for the account that you intend to use when you commit to Git.
Go to https://accounts.eclipse.org/user/eca to sign the Eclipse ECA.

### CODE REVIEW

**Comment by icraggs** [comment]
Hmm.  The test you submitted (thank you) doesn't work with these changes.

**Comment by michalkas** [comment]
Yes I saw it. But unfortunetly I did not have time to take a closer look. 
I tested it only with clang and it seemed that the issue is solved. But apparently not.
Is there a way to have backtrace or some more information about the segfault from Travis?

**Review by icraggs — CHANGES_REQUESTED** [review]
Thanks for the test, however it will need to be able to pass.  At some point I may be able to look at it.

**Comment by icraggs** [comment]
Merged now, into the develop branch.  It was just the test invocation that needed correcting.  Thanks.

**Comment by michalkas** [comment]
Thank you.

**Pull request closed without merging**
