### PR TITLE
Fix names of static libraries

### LINKED ISSUE #738: Building static libraries on linux failes
I'm using this:
```
#!/bin/bash
set -e
rm -rf build.paho
mkdir build.paho
cd build.paho
echo "travis build dir $TRAVIS_BUILD_DIR pwd $PWD"
#cmake -DCMAKE_BUILD_TYPE=Debug -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE ..
cmake -DCMAKE_BUILD_TYPE=Debug -DPAHO_BUILD_STATIC=TRUE -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE ..
make
...

```
failes with:

CMake Error at src/CMakeLists.txt:95 (ADD_LIBRARY):
  add_library cannot create target "paho-mqtt3c" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory "/10_data/55_git/paho.mqtt.c/src".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/CMakeLists.txt:96 (ADD_LIBRARY):
  add_library cannot create target "paho-mqtt3a" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory "/10_data/55_git/paho.mqtt.c/src".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/CMakeLists.txt:101 (INSTALL):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "paho-mqtt3c".
...

### PR DESCRIPTION
**Pull request by Roman3349**
Fixes #738 - a bug accidentally created by me in the commit https://github.com/eclipse/paho.mqtt.c/commit/8cc51c78b76a1eabd1df3124b0887ce8b01070ff.

### CODE REVIEW

**Comment by tbeu** [comment]
Does it fix #738?

**Comment by Roman3349** [comment]
@tbeu Yes, it does.

**Comment by tbeu** [comment]
You might edit your first post by

> fix #738

**Review by tbeu — APPROVED** [review]

**Comment by icraggs** [comment]
Thanks.

**Pull request merged**
