### PR TITLE
Fix samples

### PR DESCRIPTION
**Pull request by guilhermeferreira**

### CODE REVIEW

**Comment by stefboerrigter** [comment]
you forgot to add delimiter for --client-id:
printf("  --clientid <clientid> (default is hostname+timestamp)<HERE_SHOULD_BE_DELIMITER>");

**Comment by guilhermeferreira** [comment]
Hi Stef,

I can't see your comment on Github. Anyways, could you give me the file
where the delimiter is missing, please?

Best regards,

2016-05-10 4:58 GMT-05:00 stefboerrigter notifications@github.com:

> you forgot to add delimiter for --client-id:
> printf(" --clientid (default is hostname+timestamp)");
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/eclipse/paho.mqtt.c/pull/129#issuecomment-218112545

## 

Guilherme Maciel Ferreira
Mobile Brazil: +55 48 9917 3969
Site: http://guilhermemacielferreira.com/
Skype: guilherme.maciel.ferreira

**Comment by stefboerrigter** [comment]
I missed the next commit where it was added. So it was my mistake

Kind regards Stef.
Op 11 mei 2016 19:44 schreef "Guilherme Maciel Ferreira" <
notifications@github.com>:

**Comment by guilhermeferreira** [comment]
Ok, btw thanks for reviewing the branch.

Best regards,
Am 11.05.2016 21:12 schrieb "stefboerrigter" notifications@github.com:

**Comment by icraggs** [comment]
Thank you both.  I will be updating the samples soon, renaming them to paho_c_sub and paho_c_pub and similar, to make the naming more consistent and avoiding clashes with other paho libraries.

**Comment by icraggs** [comment]
I meant to merge!

**Pull request merged**
