### PR TITLE
Fix compilation with VS2010

### PR DESCRIPTION
**Pull request by AdrianMoranMontes**
Until VS2013, all variables should be defined at the beggining of a block. This patch solves the issue.

Signed-off-by: Adrian Moran <amoran@ikerlan.es>

### CODE REVIEW

**Comment by AdrianMoranMontes** [comment]
I see travis-ci is failing on test 40 when compiling with clang. I can not reproduce such failure in my local environment, since the test successes both, with GCC and with CLang.

Can anybody try to reproduce the error?

**Comment by tbeu** [comment]
See also #517.

**Comment by tbeu** [comment]
See also #517.

**Comment by icraggs** [comment]
Thanks.

**Comment by tbeu** [comment]
I am rather confused why you merged this outdated and incomplete PR after I wrote in https://github.com/eclipse/paho.mqtt.c/pull/517#issuecomment-558790997 that #517 supersedes this PR.

**Pull request merged**
