### PR TITLE
Fixup win32 global init

### PR DESCRIPTION
**Pull request by raffienficiaud**
This PR fixes 2 problems:

* the export of the symbols at dll boundary are erroneous: they should be ``dllexport`` when we build the library and ``dllimport`` otherwise. 
  This is now controlled by the ``MQTT_EXPORT`` define (defined when mlibrary being built, not defined otherwise).
  For the object library: since it is built all the time, we can just define the ``MQTT_EXPORT`` to 1.

  See https://cmake.org/cmake/help/v3.0/prop_tgt/DEFINE_SYMBOL.html for more information on how this is done with CMake. 

* the global mutexes creation are now inside a function called ``MQTTAsync_init`` / ``MQTTClient_init``. These functions are called by the ``DLLMain``
  to have the same behaviour as before on Windows and on other platforms, and called also by the currently exposed function ``MQTTAsync_global_init``
  ``MQTTAsync_global_init`` / ``MQTTClient_global_init``

I do not know if the call to ``MQTTAsync_init`` can be done several times without side effects on platforms other than win32. Let me know if you experience problems
with that. 

Thanks

### CODE REVIEW

**Comment by raffienficiaud** [comment]
I believe I just signed the eclipse validation. Let me know what I should do next.

**Comment by raffienficiaud** [comment]
Any chance to have a feedback?

**Comment by marton78** [comment]
@icraggs could you please restart the checks? @raffienficiaud says he now signed Eclipse validation.

**Comment by raffienficiaud** [comment]
How should I proceed? Should I resend a PR?

**Comment by icraggs** [comment]
The checks happen automatically, so the best way is to resubmit the PR, yes.

**Comment by jumoog** [comment]
any update on this?

**Comment by icraggs** [comment]
I can't merge these commits without them being signed off: 

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
raffi.enficiaud@tuebingen.mpg.de

Also, I never use the library statically - I assume both of these changes are for static use?  It would be good to have some regression tests added to the test suite for static use.  That effort would probably be more than these code changes.

**Comment by raffienficiaud** [comment]
@icraggs I updated the PR with signed commits. Let me know if this is what you were expecting.

Concerning the PR itself, 

* The changes are for dynamic and static use.
* `LIBMQTT_API` explicitly indicates the decoration of the functions during the build of the library or when the library is being pulled by another one. The `DllExport`/`DllImport` instead does not make this distinction
* The global mutexes creation is now shared between the global init functions (eg. `MQTTClient_global_init`) and the reasons for attaching the dll to another process - if I remember well.

Let me know if this is understandable. It has been quite some time since...

**Comment by raffienficiaud** [comment]
Should I do anything else?

**Comment by emgre** [comment]
Another thing to consider would be to not compile `DllMain` when doing a static build, as it can create a duplicate symbol error when linking if another library does this error.

cc @jadamcrain

**Comment by icraggs** [comment]
Merged into the develop branch.  Thanks.

**Comment by raffienficiaud** [comment]
Thanks!

**Comment by raffienficiaud** [comment]
@icraggs should I close the PR or wait?

**Comment by icraggs** [comment]
I was waiting until the Appveyor and Travis builds had completed successfully.   Which they now have.  Thanks again!

**Comment by icraggs** [comment]
@emgre maybe open another issue or PR for that?

**Comment by keysight-daryl** [comment]
this PR is a real improvement in allowing the library to be built as a static library under windows as well as fixing the dll spec.  nice work!

**Pull request closed without merging**
