### PR TITLE
if CApath is set load the PEM files

### PR DESCRIPTION
**Pull request by jumoog**
i tried to use CApath but enableServerCertAuth always failed

It happens because we never load the certs from the given path.

in 695563fccb5d3add93c46a9562dbdc9f6afa5a57 the loading option is missing

Signed-off-by: Kilian von Pflugk <github@jumoog.io>

### CODE REVIEW

**Comment by jumoog** [comment]
i signed ECA how to triger the validation again?

**Comment by jumoog** [comment]
i implemented CAfile as well but i guess thats a new feature

**Comment by icraggs** [comment]
I just noticed your comment "i implemented CAfile as well but i guess thats a new feature".  The CAfile is specified with the trustStore option (the implementer used the a general TLS term), so it's there already.  Which now lead me to think that the simplest implementation could be:

    if (opts->trustStore || opts->CApath)
	{
		if ((rc = SSL_CTX_load_verify_locations(net->ctx, opts->trustStore, opts->CApath)) != 1)
		{
			if (opts->struct_version >= 3)
				SSLSocket_error("SSL_CTX_load_verify_locations", NULL, net->socket, rc, opts->ssl_error_cb, opts->ssl_error_context);
			else
				SSLSocket_error("SSL_CTX_load_verify_locations", NULL, net->socket, rc, NULL, NULL);
			goto free_ctx;
		}
	}

In fact, I'm not sure what whether the effect of making this call a second time will override the first.

**Comment by jumoog** [comment]
you are right! i use mqtt-spy and you can use trustStore **or** CAfile.
you can't use both at the same time!

> ```
> if (opts->trustStore || opts->CApath)
> {
> 	if ((rc = SSL_CTX_load_verify_locations(net->ctx, opts->trustStore, opts->CApath)) != 1)
> 	{
> ```

**Comment by icraggs** [comment]
Hi Kilian.  Thanks for this.  The second commit for the test doesn't appear to have the signed-off-by info.  If you could add that, I will be able to merge directly.

**Comment by icraggs** [comment]
Thanks for that, Kilian.

I have been running the tests, but realised they're not correct as is.  The test numbers are not correct, so they're not running the added tests.  Also the tests are setting the CAfile option too, so that takes precedence and causes them to succeed whether CApath is set correctly or not.  I tried to get the CApath option to work but have not succeeded so far (ensure the server cert file is in PEM format, run c_rehash on the cert directory, that sort of thing.  See https://github.com/openssl/openssl/issues/4708 for more info).  I'm going to be on vacation until the 29th after tomorrow, so I won't be getting back to it until then.  I'm tempted to add the fix sooner and add the tests later when we've sorted them out.

**Comment by hitmon33** [comment]
Hello,

I am trying to connect to aws and it seems like it doesnt pick up CA file. So I am just wondering if its related to this issue and has been fixed yet? I tried to put CA file in trustStore and CAfile but none of that worked. 

20070101 094807.221 SSL cipher available: 96:DES-CBC3-SHA
20070101 094807.221 (3062305952)  (1)< Thread_wait_cond:419 (110)
20070101 094807.221 (3062305952)  (1)> MQTTAsync_checkTimeouts:1730
20070101 094807.221 SSL cipher available: 97:PSK-3DES-EDE-CBC-SHA
20070101 094807.221 (3053917344)     (4)> MQTTStrncpy:848
20070101 094807.221 the src string is truncated
20070101 094807.221 (3053917344)     (4)< MQTTStrncpy:858
20070101 094807.221 (3053917344)    (3)< SSLSocket_setSocketForSSL:686 (1)
20070101 094807.221 (3053917344)    (3)> SSLSocket_connect:697
20070101 094807.388 SSL handshake started write:unknown:unknown
20070101 094807.388 SSL state connect:before/connect initialization:(NONE)
20070101 094807.388 sent 0 256 buflen 5
20070101 094807.388 sent 771 22 buflen 356
20070101 094807.388 SSL state connect:SSLv3 write client hello A:(NONE)
20070101 094807.388 SSL connect:SSLv3 read server hello A
20070101 094807.388 (3053917344)     (4)> SSLSocket_error:97
20070101 094807.388 SSLSocket error WANT_READ/WANT_WRITE
20070101 094807.388 (3053917344)     (4)< SSLSocket_error:117 (2)
20070101 094807.388 (3053917344)    (3)< SSLSocket_connect:735 (-22)
20070101 094807.388 (3053917344)   (2)< MQTTAsync_connecting:3652 (0)
20070101 094807.388 m->c->connect_state = 2
20070101 094807.388 CONNECT sent, *rc is 0
20070101 094807.388 (3053917344)   (2)> MQTTAsync_retry:3495
20070101 094807.388 (3053917344)    (3)> MQTTProtocol_keepalive:608
20070101 094807.388 (3053917344)    (3)< MQTTProtocol_keepalive:641
20070101 094807.388 (3053917344)    (3)> MQTTProtocol_retry:727
20070101 094807.388 (3053917344)    (3)< MQTTProtocol_retry:746
20070101 094807.388 (3053917344)   (2)< MQTTAsync_retry:3505
20070101 094807.388 (3062305952)  (1)< MQTTAsync_checkTimeouts:1778
20070101 094807.525 (3062305952)  (1)> Thread_wait_cond:411
20070101 094807.525 (3053917344)  (1)< MQTTAsync_cycle:3810 (0)
20070101 094807.525 (3053917344)  (1)> MQTTAsync_cycle:3663
20070101 094807.525 (3053917344)   (2)> Socket_getReadySocket:237
20070101 094807.525 (3053917344)    (3)> Socket_continueWrites:928
20070101 094807.525 (3053917344)    (3)< Socket_continueWrites:952 (0)
20070101 094807.525 (3053917344)    (3)> isReady:213
20070101 094807.525 (3053917344)    (3)< isReady:218 (1)
20070101 094807.525 (3053917344)   (2)< Socket_getReadySocket:309 (3)
20070101 094807.525 m->c->connect_state = 2
20070101 094807.525 (3053917344)   (2)> MQTTAsync_connecting:3513
20070101 094807.525 (3053917344)    (3)> SSLSocket_connect:697
20070101 094807.525 received 0 256 buflen 5
20070101 094807.525 received 771 22 buflen 81
20070101 094807.525 SSL state connect:SSLv3 read server hello A:(NONE)
20070101 094807.525 received 771 22 buflen 4883
20070101 094807.525 sent 0 256 buflen 5
20070101 094807.525 sent 771 21 buflen 2
20070101 094807.525 SSL alert write:fatal:unknown CA
20070101 094807.525 SSL connect:error
20070101 094807.709 (3053917344)     (4)> SSLSocket_error:97
20070101 094807.709 SSLSocket error (1) in SSL_connect for socket 3 rc -1 errno 2 No such file or directory

20070101 094807.709 (3053917344)     (4)< SSLSocket_error:117 (-3)
20070101 094807.709 (3053917344)    (3)< SSLSocket_connect:735 (-3)
20070101 094807.709 (3053917344)    (3)> nextOrClose:1667
20070101 094807.709 (3053917344)     (4)> MQTTAsync_checkConn:467
20070101 094807.709 (3053917344)     (4)< MQTTAsync_checkConn:470 (0)
20070101 094807.709 (3053917344)     (4)> MQTTAsync_closeSession:2587
20070101 094807.709 (3053917344)      (5)> MQTTAsync_closeOnly:2559
20070101 094807.709 (3053917344)       (6)> MQTTProtocol_checkPendingWrites:1138
20070101 094807.709 (3053917344)       (6)< MQTTProtocol_checkPendingWrites:1155
20070101 094807.709 (3053917344)       (6)> WebSocket_close:397
20070101 094807.709 (3053917344)       (6)< WebSocket_close:450
20070101 094807.709 (3053917344)       (6)> SSLSocket_close:852

And here is my trace output. I cross-compiled to arm
                   Trace Output
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.0
Build level: Mon Jun 10 14:57:38 PDT 2019
OpenSSL version: OpenSSL 1.0.2j-fips  26 Sep 2016
OpenSSL flags: compiler: /opt/arm926_toolchain/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -O3 -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -I/usr/local/ssl/fips-2.0/include -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM
OpenSSL build timestamp: built on: reproducible build, date unspecified
OpenSSL platform: platform: linux-armv4
OpenSSL directory: OPENSSLDIR: "/usr/local/ssl"
/proc/version: Linux version 3.16.38 (root@Debian7x64) (gcc version 4.8.3 (Buildroot 2014.08) )

**Comment by jumoog** [comment]
yes i had the same problem

**Comment by icraggs** [comment]
This has been merged into develop some time ago.  Thanks!

**Comment by pashinov** [comment]
Hi @icraggs, @jumoog and @hitmon33
I faced with the same problem like @hitmon33 and even using latest version of library I can't connect to MQTT broker from my device (connection from host works fine). I noticed that my client don't react on parameter MQTTAsync_SSLOptions::trustStore and even though I don't set path to my CARoot file I can connect to IoT Hub from host but it doesn't work on my device and I get error "SSL alert write:fatal:unknown CA". Can you help me to solve this problem? I can show my trace output but it looks like report of @hitmon33 above.

**Comment by pashinov** [comment]
And one more I also can connect to broker from device by "openssl s_client -cert certs/certificate.pem.crt -key certs/private.pem.key -CAfile certs/AmazonRootCA1.pem -connect
ats.iot.eu-west-1.amazonaws.com:8883"

**Comment by pashinov** [comment]
Sorry for bothering. The problem was related to ca certificate. I can't understand why but I can't connect to AWS Core using AmazonRootCA1.pem provided by Amazon. It looks like I don't understand clearly how it works.

**Comment by hitmon33** [comment]
I think I eventually got it working. Did you check the time on your device or if the certificate is expired?

**Comment by phantom-j** [comment]
This configuration worked for me and i can receive messages also

	conn_opts.ssl = &ssl_opts;
    conn_opts.ssl->enableServerCertAuth = 1;
    conn_opts.ssl->struct_version = 3;
    conn_opts.ssl->CApath = "./*****-certificate.pem.crt";
    conn_opts.ssl->trustStore = "./AmazonRootCA1.pem";
    conn_opts.ssl->keyStore = "./******-certificate.pem.crt";
    conn_opts.ssl->privateKey = "./******-private.pem.key";
    conn_opts.ssl->sslVersion = MQTT_SSL_VERSION_TLS_1_2;

**Pull request closed without merging**
