### PR TITLE
prevent redefine of variables by VisualStudio 2013

### PR DESCRIPTION
**Pull request by dontsovcmc**
https://github.com/eclipse/paho.mqtt.c/issues/348

### CODE REVIEW

**Comment by icraggs** [comment]
This pull request seems to contain the changes for SSL options checking, as well as any for variable redefinition.

**Comment by dontsovcmc** [comment]
I commit to develop branch as written in https://github.com/eclipse/paho.mqtt.c/blob/master/CONTRIBUTING.md  :/
Should I commit to master and add defines for VS less than 2017? 

#ifdef _MSC_VER
#if (_MSC_VER < 1910)
#include <errno.h>
#endif
#endif

**Comment by icraggs** [comment]
You shouldn't need to include errno.h - I thought your issue was to avoid the redefinition of constants because of the inclusion of errno.h.  None of this should be needed as I've built versions of this code on Windows for the last 10 years, and I don't think that changing versions of Visual Studio should have such a large effect. 

I installed VS 2013 to try this out, but it seems that it's not compatible with the latest update to Windows 10, so I verify that these changes are not needed.

**Comment by JuergenKosel** [comment]
Hello @icraggs ,

please take a look at https://github.com/eclipse/paho.mqtt.c/pull/367
For Visual Studio 2010 build the current include of errno.h causes a problem in Socket_setnonblocking().

**Comment by icraggs** [comment]
Ok, errno.h should not be included in Socket.c.  It seems I missed that addition in July in a PR #a16cff63 as it was included along with many other changes, and the Appveyor build & test worked.  But the AppVeyor build uses VS2014, and I don't currently use any edition of Visual Studio older than 2015.

I'm going to make myself a coffee :-(

**Comment by icraggs** [comment]
#367 should fix this problem.

**Comment by dontsovcmc** [comment]
yes

**Pull request closed without merging**
