### PR TITLE
Fix Cygwin build

### LINKED ISSUE #568: Error during make on Cygwin
Hello,
I'm trying to compile the project on Windows 10 with cygwin.

I have cloned the repo and when I execute the line "make". I'm getting the following errors;

> $ make
mkdir -p build/output/samples
mkdir -p build/output/test
echo OSTYPE is Windows_NT
OSTYPE is Windows_NT
cc -g -fPIC  -Os -Wall -fvisibility=hidden -Ibuild  -o build/output/libpaho-mqtt3c.so.1.0 src/Tree.c src/SocketBuffer.c src/utf-8.c src/MQTTReasonCodes.c src/LinkedList.c src/MQTTPersistence.c src/Log.c src/MQTTClient.c src/SHA1.c src/Thread.c src/OsWrapper.c src/Clients.c src/WebSocket.c src/MQTTPacketOut.c src/Messages.c src/MQTTPersistenceDefault.c src/MQTTProtocolClient.c src/MQTTProperties.c src/Base64.c src/StackTrace.c src/MQTTProtocolOut.c src/MQTTPacket.c src/Socket.c src/Heap.c  -shared -Wl,-init, -lpthread
src/SHA1.c: In function ‘SHA1_ProcessBlock’:
src/SHA1.c:109:10: warning: implicit declaration of function ‘be32toh’ [-Wimplicit-function-declaration]
   w[i] = be32toh(w[i]);
          ^~~~~~~
src/SHA1.c: In function ‘SHA1_Final’:
src/SHA1.c:156:15: warning: implicit declaration of function ‘htobe32’ [-Wimplicit-function-declaration]
  ctx->w[14] = htobe32((uint32_t)(total >> 32));
               ^~~~~~~
src/StackTrace.c: In function ‘StackTrace_entry’:
src/StackTrace.c:110:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
src/StackTrace.c: In function ‘StackTrace_exit’:
src/StackTrace.c:134:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
src/StackTrace.c:136:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
/tmp/cceX9sG9.o: In function `SHA1_ProcessBlock':
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109: undefined reference to `be32toh'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109:(.text+0x48): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
/tmp/cceX9sG9.o: In function `SHA1_Final':
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156:(.text+0x256): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:157: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:157:(.text+0x262): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:162: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:162:(.text+0x275): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make: *** [Makefile:245: build/output/libpaho-mqtt3c.so.1.0] Error 

I'm guessing there is a problem with OpenSSL but I couldn't figure out how to make it work.

when I try " cmake -G "Unix Makefiles" /home/soulflyer/paho.mqtt.c -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_STATIC=TRUE -DOPENSSL_SEARCH_PATH=/usr/local"

> --CMake version: 3.6.2
-- CMake system name: CYGWIN
-- Timestamp is 2018-10-22T21:18:14Z
-- OpenSSL hints: /usr/local
-- OpenSSL headers found at /usr/local/include
-- OpenSSL library found at /lib/libssl.dll.a
-- OpenSSL Crypto library found at /lib/libcrypto.dll.a
-- OpenSSL hints: /usr/local
-- OpenSSL headers found at /usr/local/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/soulflyer/paho.mqtt.c/build

And then when I use "make" under build folder

> $ make
[ 22%] Built target common_obj
Scanning dependencies of target paho-mqtt3a
[ 23%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.o
[ 24%] Linking C shared library cygpaho-mqtt3a-1.dll
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): undefined reference to `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/paho-mqtt3a.dir/build.make:139: src/cygpaho-mqtt3a-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: src/CMakeFiles/paho-mqtt3a.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

Thanks for your help

### PR DESCRIPTION
**Pull request by tbeu**
Fix CygWin build (only tested with `-DPAHO_WITH_SSL=FALSE`).

close #568

### CODE REVIEW

**Comment by tbeu** [comment]
Update: Also confirmed to build with `-DPAHO_WITH_SSL=TRUE`

> $ make
```
[  1%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolClient.c.o
[  2%] Building C object src/CMakeFiles/common_obj.dir/Clients.c.o
[  3%] Building C object src/CMakeFiles/common_obj.dir/utf-8.c.o
[  4%] Building C object src/CMakeFiles/common_obj.dir/StackTrace.c.o
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c: In Funktion »StackTrace_entry«:
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c:110:34: Warnung: Typkonvertierung von Zeiger auf Ganzzahl anderer Breite [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c: In Funktion »StackTrace_exit«:
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c:134:36: Warnung: Typkonvertierung von Zeiger auf Ganzzahl anderer Breite [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c:136:36: Warnung: Typkonvertierung von Zeiger auf Ganzzahl anderer Breite [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
[  5%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacket.c.o
[  6%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacketOut.c.o
[  7%] Building C object src/CMakeFiles/common_obj.dir/Messages.c.o
[  8%] Building C object src/CMakeFiles/common_obj.dir/Tree.c.o
[  9%] Building C object src/CMakeFiles/common_obj.dir/Socket.c.o
[ 10%] Building C object src/CMakeFiles/common_obj.dir/Log.c.o
[ 11%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistence.c.o
[ 11%] Building C object src/CMakeFiles/common_obj.dir/Thread.c.o
[ 12%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolOut.c.o
[ 13%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.o
[ 15%] Building C object src/CMakeFiles/common_obj.dir/SocketBuffer.c.o
[ 16%] Building C object src/CMakeFiles/common_obj.dir/Heap.c.o
[ 17%] Building C object src/CMakeFiles/common_obj.dir/LinkedList.c.o
[ 18%] Building C object src/CMakeFiles/common_obj.dir/MQTTProperties.c.o
[ 19%] Building C object src/CMakeFiles/common_obj.dir/MQTTReasonCodes.c.o
[ 20%] Building C object src/CMakeFiles/common_obj.dir/Base64.c.o
[ 21%] Building C object src/CMakeFiles/common_obj.dir/SHA1.c.o
[ 22%] Building C object src/CMakeFiles/common_obj.dir/WebSocket.c.o
[ 22%] Built target common_obj
[ 23%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.o
[ 24%] Linking C shared library cygpaho-mqtt3a-1.dll
[ 24%] Built target paho-mqtt3a
[ 25%] Building C object src/CMakeFiles/paho-mqtt3a-static.dir/MQTTAsync.c.o
[ 26%] Linking C static library libpaho-mqtt3a-static.a
[ 26%] Built target paho-mqtt3a-static
[ 27%] Building C object src/CMakeFiles/paho-mqtt3c-static.dir/MQTTClient.c.o
[ 29%] Linking C static library libpaho-mqtt3c-static.a
[ 29%] Built target paho-mqtt3c-static
[ 30%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTProtocolClient.c.o
[ 31%] Building C object src/CMakeFiles/common_ssl_obj.dir/Clients.c.o
[ 32%] Building C object src/CMakeFiles/common_ssl_obj.dir/utf-8.c.o
[ 33%] Building C object src/CMakeFiles/common_ssl_obj.dir/StackTrace.c.o
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c: In Funktion »StackTrace_entry«:
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c:110:34: Warnung: Typkonvertierung von Zeiger auf Ganzzahl anderer Breite [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c: In Funktion »StackTrace_exit«:
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c:134:36: Warnung: Typkonvertierung von Zeiger auf Ganzzahl anderer Breite [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
/cygdrive/c/Projects/paho.mqtt.c/src/StackTrace.c:136:36: Warnung: Typkonvertierung von Zeiger auf Ganzzahl anderer Breite [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
[ 34%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPacket.c.o
[ 35%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPacketOut.c.o
[ 36%] Building C object src/CMakeFiles/common_ssl_obj.dir/Messages.c.o
[ 37%] Building C object src/CMakeFiles/common_ssl_obj.dir/Tree.c.o
[ 38%] Building C object src/CMakeFiles/common_ssl_obj.dir/Socket.c.o
[ 39%] Building C object src/CMakeFiles/common_ssl_obj.dir/Log.c.o
[ 39%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPersistence.c.o
[ 40%] Building C object src/CMakeFiles/common_ssl_obj.dir/Thread.c.o
[ 41%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTProtocolOut.c.o
[ 43%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPersistenceDefault.c.o
[ 44%] Building C object src/CMakeFiles/common_ssl_obj.dir/SocketBuffer.c.o
[ 45%] Building C object src/CMakeFiles/common_ssl_obj.dir/Heap.c.o
[ 46%] Building C object src/CMakeFiles/common_ssl_obj.dir/LinkedList.c.o
[ 47%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTProperties.c.o
[ 48%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTReasonCodes.c.o
[ 49%] Building C object src/CMakeFiles/common_ssl_obj.dir/Base64.c.o
[ 50%] Building C object src/CMakeFiles/common_ssl_obj.dir/SHA1.c.o
[ 51%] Building C object src/CMakeFiles/common_ssl_obj.dir/WebSocket.c.o
[ 51%] Built target common_ssl_obj
[ 52%] Building C object src/CMakeFiles/paho-mqtt3cs.dir/MQTTClient.c.o
[ 53%] Building C object src/CMakeFiles/paho-mqtt3cs.dir/SSLSocket.c.o
[ 54%] Linking C shared library cygpaho-mqtt3cs-1.dll
[ 54%] Built target paho-mqtt3cs
[ 55%] Building C object src/CMakeFiles/paho-mqtt3c.dir/MQTTClient.c.o
[ 56%] Linking C shared library cygpaho-mqtt3c-1.dll
[ 56%] Built target paho-mqtt3c
Scanning dependencies of target MQTTVersion
[ 58%] Building C object src/CMakeFiles/MQTTVersion.dir/MQTTVersion.c.o
[ 59%] Linking C executable MQTTVersion.exe
[ 59%] Built target MQTTVersion
[ 60%] Building C object src/CMakeFiles/paho-mqtt3as.dir/MQTTAsync.c.o
[ 61%] Building C object src/CMakeFiles/paho-mqtt3as.dir/SSLSocket.c.o
[ 62%] Linking C shared library cygpaho-mqtt3as-1.dll
[ 62%] Built target paho-mqtt3as
[ 63%] Building C object src/CMakeFiles/paho-mqtt3cs-static.dir/MQTTClient.c.o
[ 64%] Building C object src/CMakeFiles/paho-mqtt3cs-static.dir/SSLSocket.c.o
[ 65%] Linking C static library libpaho-mqtt3cs-static.a
[ 65%] Built target paho-mqtt3cs-static
[ 66%] Building C object src/CMakeFiles/paho-mqtt3as-static.dir/MQTTAsync.c.o
[ 67%] Building C object src/CMakeFiles/paho-mqtt3as-static.dir/SSLSocket.c.o
[ 67%] Linking C static library libpaho-mqtt3as-static.a
[ 67%] Built target paho-mqtt3as-static
[ 68%] Building C object test/CMakeFiles/test4.dir/test4.c.o
[ 69%] Linking C executable test4.exe
[ 69%] Built target test4
[ 70%] Building C object test/CMakeFiles/test1.dir/test1.c.o
[ 72%] Linking C executable test1.exe
[ 72%] Built target test1
[ 73%] Building C object test/CMakeFiles/test6.dir/test6.c.o
[ 74%] Linking C executable test6.exe
[ 74%] Built target test6
[ 75%] Building C object test/CMakeFiles/test2.dir/test2.c.o
[ 76%] Linking C executable test2.exe
[ 76%] Built target test2
[ 77%] Building C object test/CMakeFiles/test11.dir/test11.c.o
[ 78%] Linking C executable test11.exe
[ 78%] Built target test11
[ 79%] Building C object test/CMakeFiles/test15.dir/test15.c.o
[ 80%] Linking C executable test15.exe
[ 80%] Built target test15
[ 81%] Building C object test/CMakeFiles/thread.dir/thread.c.o
[ 82%] Building C object test/CMakeFiles/thread.dir/__/src/Thread.c.o
[ 83%] Linking C executable thread.exe
[ 83%] Built target thread
[ 84%] Building C object test/CMakeFiles/test45.dir/test45.c.o
[ 86%] Linking C executable test45.exe
[ 86%] Built target test45
[ 87%] Building C object test/CMakeFiles/test5.dir/test5.c.o
[ 88%] Linking C executable test5.exe
[ 88%] Built target test5
[ 89%] Building C object test/CMakeFiles/test8.dir/test8.c.o
[ 90%] Linking C executable test8.exe
[ 90%] Built target test8
[ 90%] Building C object test/CMakeFiles/test3.dir/test3.c.o
[ 91%] Linking C executable test3.exe
[ 91%] Built target test3
[ 92%] Building C object test/CMakeFiles/test9.dir/test9.c.o
[ 93%] Linking C executable test9.exe
[ 93%] Built target test9
[ 94%] Building C object test/CMakeFiles/test95.dir/test95.c.o
[ 95%] Linking C executable test95.exe
[ 95%] Built target test95
[ 96%] Building C object test/CMakeFiles/test10.dir/test10.c.o
[ 97%] Linking C executable test10.exe
[ 97%] Built target test10
[ 98%] Building C object test/CMakeFiles/test_issue373.dir/test_issue373.c.o
[100%] Linking C executable test_issue373.exe
[100%] Built target test_issue373
```
> $ ./src/MQTTVersion.exe
```
MQTTVersion: print the version strings of an MQTT client library
Copyright (c) 2012, 2018 IBM Corp.
Specify a particular library name if it is not in the current directory, or not executable on this platform
--- Trying library paho-mqtt3c ---
Product name: Eclipse Paho Synchronous MQTT C Client Library
Version: 1.3.0
Build level: 2018-11-26T20:07:24Z
--- Trying library paho-mqtt3cs ---
Product name: Eclipse Paho Synchronous MQTT C Client Library
Version: 1.3.0
Build level: 2018-11-26T20:07:24Z
OpenSSL version: OpenSSL 1.0.2p  14 Aug 2018
OpenSSL flags: compiler: gcc -I. -I.. -I../include  -D_WINDLL -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS  -DDSO_DLFCN -DHAVE_DLFCN_H -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/home/corinna/src/openssl/openssl-1.0.2p/openssl-1.0.2p-1.x86_64/build=/usr/src/debug/openssl-1.0.2p-1 -fdebug-prefix-map=/home/corinna/src/openssl/openssl-1.0.2p/openssl-1.0.2p-1.x86_64/src/openssl-1.0.2p=/usr/src/debug/openssl-1.0.2p-1 -DTERMIOS -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OpenSSL build timestamp: built on: reproducible build, date unspecified
OpenSSL platform: platform: Cygwin-x86_64
OpenSSL directory: OPENSSLDIR: "/usr/ssl"
--- Trying library paho-mqtt3a ---
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.0
Build level: 2018-11-26T20:07:24Z
--- Trying library paho-mqtt3as ---
Product name: Eclipse Paho Asynchronous MQTT C Client Library
Version: 1.3.0
Build level: 2018-11-26T20:07:24Z
OpenSSL version: OpenSSL 1.0.2p  14 Aug 2018
OpenSSL flags: compiler: gcc -I. -I.. -I../include  -D_WINDLL -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS  -DDSO_DLFCN -DHAVE_DLFCN_H -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/home/corinna/src/openssl/openssl-1.0.2p/openssl-1.0.2p-1.x86_64/build=/usr/src/debug/openssl-1.0.2p-1 -fdebug-prefix-map=/home/corinna/src/openssl/openssl-1.0.2p/openssl-1.0.2p-1.x86_64/src/openssl-1.0.2p=/usr/src/debug/openssl-1.0.2p-1 -DTERMIOS -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OpenSSL build timestamp: built on: reproducible build, date unspecified
OpenSSL platform: platform: Cygwin-x86_64
OpenSSL directory: OPENSSLDIR: "/usr/ssl"
```

**Comment by tbeu** [comment]
Rebased and successfully tested with v1.3.1.

**Comment by austenstone** [comment]
When will this get merged in?

**Comment by tbeu** [comment]
I offered @icraggs to take care of the Win ports several months ago but got no reply other than he's too busy with other projects. Obviously, that's the reason why so many PRs are defered.

**Comment by icraggs** [comment]
Thanks.

**Pull request merged**
