### PR TITLE
Fix issue #572

### PR DESCRIPTION
**Pull request by aggresss**
Fix issue #572 
Segmentation fault when sending a lot of messages from two threads

### CODE REVIEW

**Comment by aggresss** [comment]
add mutex lock for commands on these functions:
1. MQTTAsync_restoreCommands()
2. MQTTAsync_removeResponsesAndCommands()
3. MQTTAsync_assignMsgId()
4. MQTTAsync_countBufferedMessages()
5. MQTTAsync_getPendingTokens() 
6. MQTTAsync_isComplete()

**Comment by icraggs** [comment]
Hi.  As you can see, this change causes the existing CI tests to fail.  

Also you'll need to sign the Eclipse ECA and each commit as outlined in the PULL_REQUEST_TEMPLATE.md to allow the IP check to pass.

**Review by icraggs — COMMENTED** [review]
Issue #572 should be fixed by locking the command mutex in countBufferedMessages, nothing more.

**Review by icraggs — COMMENTED** [review]
Thanks for signing the ECA and the commits.  When fixing an issue, I prefer to focus on the minimum fix needed rather than throwing in other changes too.   The other changes might be good, but also risk unintended side effects as appear to have happened here, as the CI tests are all failing.

**Review by icraggs — CHANGES_REQUESTED** [review]
CI tests need to work.

**Comment by icraggs** [comment]
I've added a fix for #572 specifically, for which the CI tests work.  If any other locking is needed you could put those into another PR, but the CI tests must work.  Thanks.

**Pull request closed without merging**
