### PR TITLE
Fix MQTTAsync_waitForCompletion(): missing MQTTAsync_unlock_mutex() call

### PR DESCRIPTION
**Pull request by matthiasklein**
Signed-off-by: Matthias Klein <matthias.klein@linux.com>

### CODE REVIEW

**Comment by icraggs** [comment]
Thanks.  You'll need to sign an Eclipse CLA for me to merge this automatically, otherwise I can add the change myself.

"The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.
matthias.klein@linux.com"

**Comment by matthiasklein** [comment]
I signed the ECA after creating the pull request, the page says: "The Eclipse Contributor Agreement that we have on record for you will expire on 2020-07-20."

Can we update the ECA state of the pull request?

**Comment by icraggs** [comment]
That's fine - I've checked you now have a valid CLA.  We're good to go.

**Comment by icraggs** [comment]
Merged into the develop branch.  Thanks.

**Pull request closed without merging**
