### PR TITLE
Bugfix in paho_cs_pub.c and paho_cs_sub.c

### PR DESCRIPTION
**Pull request by Ashechol**
In the function **MQTTClient_connect()**, first variable **client** should be MQTTClient type, but in function **myconnect()** var client is a pointer of MQTTClient type. So I think it should be *client.
Signed-off-by: Ashechol <ashechol@qq.com>

### CODE REVIEW

**Comment by icraggs** [comment]
Thanks.  

I think the fix should rather be the parameter to myconnect should be of type MQTTClient, not MQTTClient*, similar to paho_c_pub.c.

This applies to paho_cs_sub.c too.

**Comment by Ashechol** [comment]
Thanks for your advice，I have fixed my mistake.

**Comment by litdemon** [comment]
It hasn't been fixed yet. In paho_cs_sub.c's main() function. myconnect() is called twice in different ways. myconnect(client) and myconnect(&client).

**Comment by Ashechol** [comment]
Thanks a lot，I also fixed the myconnect function in paho_cs_sub.c

**Comment by icraggs** [comment]
I've merged these changes into the develop branch.  Thanks.

**Pull request closed without merging**
