### PR TITLE
Add support for AppVeyor

### PR DESCRIPTION
**Pull request by orpiske**
This PR is a follow up on [PR 225](https://github.com/eclipse/paho.mqtt.c/pull/225) and improve support for building the project on Windows as well as enable support for AppVeyor (an online CI that can be used to build projects on Windows). 

The test code is not executed automatically during build and support for this requires additional automation. However, the execution of the tests should be the same as in other OSes, provided a MQTT broker is available.

### CODE REVIEW

**Comment by orpiske** [comment]
I am currently reworking this patch so that it works better with the recent changes on the development branch.

**Comment by icraggs** [comment]
I've made some changes in the fixes branch based on this PR which allows the CMake build to finish cleanly 

https://ci.appveyor.com/project/icraggs/paho-mqtt-c-t6duj/build/1.0.3

:-)

Now we need the tests to run, which is what I'm going to look at next.  Does what you are looking at affect this?

**Comment by orpiske** [comment]
@icraggs that's great! What I am looking at is not affected by this. I reworked this patch because it was dependent on PR 225 (which was merged). I wanted to simplify/reduce the amount of changes contained here to just the minimum requirements for running on Windows along with CMake.

**Comment by icraggs** [comment]
The IP validation on this PR failed - 

"The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
orpiske"

Can you fix please?

**Comment by orpiske** [comment]
@icraggs absolutely. For some reason, it is complaining that I used a different ID to sign it off, even though I signed w/ my professional ID. I will fix it.

**Comment by icraggs** [comment]
To allow Mosquitto to be installed for local testing we could add it to Chocolatey.  I assume there isn't a reason not to?

**Comment by orpiske** [comment]
I apologize for the duplicate response, but for the sake of keeping an open record, I would say Chocolatey would be very nice for this purpose. It also integrates very well w/ AppVeyor.

**Comment by orpiske** [comment]
Closing this PR ... @icraggs patches on development branch are cleaner than this and in a more advanced state.

**Pull request closed without merging**
