### PR TITLE
Fix parsing Websocket frames

### LINKED ISSUE #609: MQTT client disconnecting while continuously publishing
I'm currently doing refactoring by moving away from mosquitto to paho as there is no websocket support in mosquitto library. Library used in my case is paho-cpp with async client, but I believe problems lies somewhere in paho-c.

mqtt keepalive: 5 seconds
broker: EMQ at localhost 
connection: websockets (no SSL)
paho-c version: v1.3.0

```
20190130 201356.879 5 MacBook-Pro.local -> PINGREQ (0)
20190130 201356.881 5 MacBook-Pro.local <- PINGRESP
20190130 201358.210 5 MacBook-Pro.local -> PUBLISH qos: 0 retained: 1 (0)
20190130 201358.211 5 MacBook-Pro.local -> PUBLISH qos: 0 retained: 1 (0)
20190130 201358.211 5 MacBook-Pro.local -> PUBLISH qos: 0 retained: 1 (0)
20190130 201358.211 5 MacBook-Pro.local -> PUBLISH qos: 0 retained: 1 (0)
20190130 201402.000 5 MacBook-Pro.local -> PINGREQ (0)
20190130 201403.999 PINGRESP not received in keepalive interval for client MacBook-Pro.local on socket 5, disconnecting
20190130 201404.000 5 MacBook-Pro.local -> DISCONNECT (0)
```

When sending same data with mosquitto library no disconnection happens at all.
Also, when no data is published there is no missing PINGRESP.

### PR DESCRIPTION
**Pull request by piotrwach**
Fixes #609

### CODE REVIEW

**Comment by icraggs** [comment]
Thanks.  

All of the test runs fail on test8-4-send-receive-big-messages, so it looks like something needs to be fixed.

Also, what tests would we need to add to show that these changes fix the problem?

**Comment by piotrwach** [comment]
I will try to see what is wrong, and think about adding a test that verifies that this fixes the problem.

**Comment by piotrwach** [comment]
@icraggs are there any existing tests for websockets?

**Comment by piotrwach** [comment]
hmm, looks like there are some tests, but they are not executed in CI

**Comment by piotrwach** [comment]
I am not able to reproduce the problem I have seen with existing tests.

**Comment by icraggs** [comment]
Merged into the develop branch.  Thanks!

**Pull request closed without merging**
