### PR TITLE
Allow proxy credentials with @ and special characters by decoding url-encoded https_proxy

### PR DESCRIPTION
**Pull request by frbouvi**

### CODE REVIEW

**Review by icraggs — CHANGES_REQUESTED** [review]
Hi, thanks.  Could you just add some comments in the code before the new section about what it does please?  I think that will be helpful for maintenance in the future.

**Comment by frbouvi** [comment]
Hi, I added some comments in the code and changed a bit the code

**Comment by icraggs** [comment]
Hi.  Unfortunately now it looks like it needs to be rebased, and the commits have the signed-off-by option.

**Comment by frbouvi** [comment]
Hi, can you give me advise. As far as I can tell, by clicking on the details, the problem is with your old email address (the ibm one) :

Anonymous (icraggs@****.ibm) is not covered by the necessary legal agreements in order to proceed.

**Comment by frbouvi** [comment]
should i recreate a new branch and a new pull request ?

**Comment by icraggs** [comment]
> Hi, can you give me advise. As far as I can tell, by clicking on the details, the problem is with your old email address (the ibm one) :
> 
> Anonymous (icraggs@****.ibm) is not covered by the necessary legal agreements in order to proceed.

Ah, that's weird.  

> should i recreate a new branch and a new pull request ?

That may well be the easiest way.

**Comment by frbouvi** [comment]
Pull request #827 has been created

De : Ian Craggs <notifications@github.com>
Envoyé : vendredi 20 mars 2020 11:45
À : eclipse/paho.mqtt.c <paho.mqtt.c@noreply.github.com>
Cc : Frederic BOUVIER <frederic.bouvier@technilog.com>; Author <author@noreply.github.com>
Objet : Re: [eclipse/paho.mqtt.c] Allow proxy credentials with @ and special characters by decoding url-encoded https_proxy (#816)


Hi, can you give me advise. As far as I can tell, by clicking on the details, the problem is with your old email address (the ibm one) :

Anonymous (icraggs@****.ibm<mailto:icraggs@****.ibm>) is not covered by the necessary legal agreements in order to proceed.

Ah, that's weird.

should i recreate a new branch and a new pull request ?

That may well be the easiest way.

**Pull request closed without merging**
