### PR TITLE
Added optional PKCS#11 Support

### PR DESCRIPTION
**Pull request by cstaylor**
This will add optional support for the PKCS#11 interface with openssl. Users can leverage this to work with any HSM that supports the PKCS#11 interface.

Tests bring in SoftHSM2
Signed-off-by: Christopher Taylor cstaylor@argo.ai

### CODE REVIEW

**Comment by robpottify** [comment]
Hey. Just looking to see what the timeline is for this change? 
Anything we can do to help?

**Comment by cstaylor** [comment]
Yes if you could you fix the `.travis.yml` file issue above that would be very helpful.

**Comment by chan-vince** [comment]
To bring the `.travis.yml` file up to date and fix the conflict, you just need to update the environment variables to include a recent `PAHO_HIGH_PERFORMANCE` addition:

```yaml
jobs:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      env: OPENSSL_ROOT_DIR= PAHO_BUILD_STATIC=TRUE PAHO_BUILD_SHARED=FALSE PAHO_HIGH_PERFORMANCE=FALSE PAHO_WITH_SSL_PKCS11=TRUE
    - os: linux
      compiler: gcc
      dist: xenial
      env: OPENSSL_ROOT_DIR= PAHO_BUILD_STATIC=TRUE PAHO_BUILD_SHARED=TRUE PAHO_HIGH_PERFORMANCE=TRUE PAHO_WITH_SSL_PKCS11=TRUE
    - os: osx
      compiler: clang
      env: OPENSSL_ROOT_DIR=/usr/local/opt/openssl PAHO_BUILD_STATIC=FALSE PAHO_BUILD_SHARED=TRUE PAHO_HIGH_PERFORMANC=FALSE
    - os: linux
      compiler: gcc
      dist: trusty
      env: OPENSSL_ROOT_DIR= PAHO_BUILD_STATIC=FALSE PAHO_BUILD_SHARED=TRUE PAHO_HIGH_PERFORMANCE=FALSE PAHO_WITH_SSL_PKCS11=TRUE
```

Note there's a spelling error in the OSX one, which I've made a PR for at #1156.

**Comment by cstaylor** [comment]
So it looks like I need to reissue the PR with the `cstaylor-argo` account instead of just the commits?

**Comment by argo-cstaylor** [comment]
Can someone close this PR for me?  I'll issue a new one with the above rules.

**Pull request closed without merging**
