### PR TITLE
Full porting to mbedTLS library (2.13.0 version).

### PR DESCRIPTION
**Pull request by AdrianMoranMontes**
These changes allow to use mbedTLS library (2.13.0 version) as TLS layer instead of OpenSSL. To do this, internal SSLSocket API has been changed in order to work with a general struct (SSL handler) instead of with OpenSSL specific objects.

CMakeList has been modified to support two compilation alternatives:
`PAHO_WITH_OPENSSL to compile it with Openssl`
`PAHO_WITH_MBEDTLS to compile it with mbedTLS`

Openssl has been set (in CMake and in the code) as default TLS layer if both were available.

**This porting has been successfully tested on Linux and Windows.**

TODO:
- [ ] Select ciphers to be used in mbedTLS.
The field `enabledCipherSuites` of struct `MQTTClient_SSLOptions` is too tied to Openssl library. It should be necessary to translate the list of ciphers from Openssl syntax to mbedTLS or, better, define a Paho specific ciphersuites and traslate them to each library syntax.
Currently, default ciphers are used when mbedTLS is selected.

Signed-off-by: Adrian Moran <amoran@ikerlan.es>

### CODE REVIEW

**Comment by AdrianMoranMontes** [comment]
Sorry, there was a bug on OpenSSL compilation due to the merge with ca27945364e02fedd145088b8d676a5d3b008f13 commit. It is fixed now.

**Comment by AdrianMoranMontes** [comment]
Fix a bug found when sending too large payloads (over 16KB).

**Comment by AdrianMoranMontes** [comment]
Merge current develop branch in order to allow automatic tests to be passed.

**Comment by tbeu** [comment]
In https://github.com/tbeu/paho.mqtt.c/commit/315dfbf4fdcdb23f43d65513bdd0d5503aab719c I configured [Travis CI](https://travis-ci.org/tbeu/paho.mqtt.c/builds/424961887) to run the test suite also with [mbedTLS 2.12.0](https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.12.0). You can see that there are 10 out of 81 tests failing now
```
The following tests FAILED:
	 17 - test3-2as-mutual-ssl-auth-single-thread (Failed)
	 18 - test3-2am-mutual-ssl-auth-multi-thread (Failed)
	 21 - test3-3as-broker-auth-server-cert-in-client-store-single-thread (Failed)
	 22 - test3-3am-broker-auth-server-cert-in-client-store-multi-thread (Failed)
	 24 - test3-4s-broker-auth-accept-invalid-certificate-single-thread (Failed)
	 25 - test3-4m-broker-auth-accept-invalid-certificate-multi-thread (Failed)
	 43 - test5-2a-multual-ssl-auth-certificates-in-place (Failed)
	 46 - test5-2d-multual-ssl-auth-client-missing-client-cert (Failed)
	 47 - test5-3a-server-auth-server-cert-in-client-store (Failed)
	 49 - test5-4-accept-invalid-certificates (Failed)
Errors while running CTest
```
Here is the occurence of the first error: https://travis-ci.org/tbeu/paho.mqtt.c/jobs/424961891#L2992-L2997

**Comment by tbeu** [comment]
Argh, there is now a merge conflict regarding the develop branch.

@AdrianMoranMontes You can cherry-pick my commit to have the Travis CI set up in your branch.

@icraggs Do you consider mbedTLS as alternative layer?

**Comment by icraggs** [comment]
I'm happy to look at this, but I need to finish off the current MQTT V5 (1.3) release first.

**Comment by tbeu** [comment]
mbedTLS [v2.13.0](https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.13.0) is released.

**Comment by AdrianMoranMontes** [comment]
> Argh, there is now a merge conflict regarding the develop branch.
> 
> @AdrianMoranMontes You can cherry-pick my commit to have the Travis CI set up in your branch.
> 
> @icraggs Do you consider mbedTLS as alternative layer?

Cherry picked! I will start debugging now.

**Comment by tbeu** [comment]
You can update `git clone --depth 5 --branch mbedtls-2.12.0 https://github.com/ARMmbed/mbedtls` to 2.13.0 then.

**Comment by AdrianMoranMontes** [comment]
Hi @tbeu and @icraggs.
I commited some changes to the work. Effectively, there was some bugs with the porting that have been fixed. I have also merged the work with last changes of Paho project in development branch and updated Travis to use mbedTLS 2.13.1 version.

You will see that some tests still fail, but those tests **should fail** in the conditions they are launched. The CA key used to sign certificates employed in the tests is a **1024 bits RSA**, which is considered **obsolete and insecure**. Under these conditions, mbedTLS library rejects the handshake (there is a dedicated error to let user know that the length of the key is not enought to be considered secure). Now that I have found the failure, I could easily overcome it (forcing mbedTLS to accept such insecure key), but I think that a better approach would be to update the certificates used for testing.

For my debugging process, I generated new set of certificates (with 4096 bit RSA key), CA, server and client.
If you replace the old certificates (both, in test broker and in Paho client), all tests will pass successfully.

You can find the certificates in the `.tar.gz` attached below: [ssl_new.tar.gz](https://github.com/eclipse/paho.mqtt.c/files/2415556/ssl_new.tar.gz)


Finally, I see that there are some issues with the ip-validation check. I can not access to the details so I can not see if those issues are related to my work. Let me know if I can help anywhere.

Thank you so much.

Adrian M.

**Comment by AdrianMoranMontes** [comment]
I see that there are issues with the signed-off of some of my comits, but I do not see on which. All commits I performed carries the Signed-off line. Is may be the issue  with the commit cheery picked from @tbeu repository?

Please, let me know how to fix the issue.

**Comment by AdrianMoranMontes** [comment]
On the other hand, CI test effectively continue failing. Let me know if testing certificates upgrading is planned or you preffer me to do a workaround to let mbedTLS work with insecure certificates. As I suggested, I think that current behaviour is the correct (fail with insecure signing keys).

Just some links:
https://knowledge.digicert.com/generalinformation/INFO1684.html
https://blog.mozilla.org/security/2014/09/08/phasing-out-certificates-with-1024-bit-rsa-keys/

Thank you so much.

**Comment by tbeu** [comment]
Argh, I forgot to add the signed-off in my commit. Can you rewrite history in your PR by removing my commit?

**Comment by AdrianMoranMontes** [comment]
@tbeu I could not rewrite the history without making the repo a mess. I applyed your changes in CI and redo cherry picked the other commits.

Please, feel free to test the work and give me some feedback.

(_Remember to update SSL certificates to make it work_)

**Comment by icraggs** [comment]
Replaced by #826

**Pull request closed without merging**
