### PR TITLE
add new option to use Windows Certificate Store

### LINKED ISSUE #923: Load root certificates from Windows Certificate Store
**Is your feature request related to a problem? Please describe.**
I use Pahoo MQTT very often under windows and the CA verification often causes problems. Especially with self signed company certificates.

**Describe the solution you'd like**
load root certificates from Windows Certificate Store for CA verification.

**Additional context**
This can be done by using the CryptoAPI functions

### PR DESCRIPTION
**Pull request by jumoog**
It's only available for Windows builds and off by default.

Thank you for your interest in this project managed by the Eclipse Foundation.

The guidelines for contributions can be found in the CONTRIBUTING.md file.

At a minimum, you must sign the Eclipse ECA, and sign off each commit.  

To complete and submit a ECA, log into the Eclipse projects forge 
You will need to create an account with the Eclipse Foundation if you have not already done so.
Be sure to use the same email address when you register for the account that you intend to use when you commit to Git.
Go to https://accounts.eclipse.org/user/eca to sign the Eclipse ECA.

### CODE REVIEW

**Comment by jumoog** [comment]
tested with ssl://broker.emqx.io:8883 

useWindowsCaStore = 0 -> CA Verify failed
useWindowsCaStore = 1 -> CA Verify passed

pull request for #923

**Comment by jumoog** [comment]
source: https://android.googlesource.com/platform/external/wpa_supplicant/+/refs/heads/master/tls_openssl.c

**Comment by icraggs** [comment]
Thank you.  Looks good.

**Comment by jumoog** [comment]
i'll do some cleanup

**Comment by jumoog** [comment]
@icraggs i'm working on a testcase for windows ca. It's okay to use `ssl://test.mosquitto.org:8081` for the Test? Port 8081 has a Lets Encrypt certificate.
As a test, i would try to connect to the broker. Once without useWindowsCaStore and once with useWindowsCaStore. The connection without useWindowsCaStore should fail and with useWindowsCaStore the connection should work.

**Comment by icraggs** [comment]
> @icraggs i'm working on a testcase for windows ca. It's okay to use `ssl://test.mosquitto.org:8081` for the Test? Port 8081 has a Lets Encrypt certificate.
> As a test, i would try to connect to the broker. Once without useWindowsCaStore and once with useWindowsCaStore. The connection without useWindowsCaStore should fail and with useWindowsCaStore the connection should work.

I'd prefer to use the Paho test broker like all the other tests.   I presume this only changes where the certificates are stored, so the same certificates should be able to be used as are for the other TLS/SSL tests?

**Comment by jumoog** [comment]
I don't have a good test case for this patch and since I need my own fork anyway I'll just maintain the patch at my fork.

**Comment by jumoog** [comment]
This code has been used in production for more than 2 years.

**Comment by jumoog** [comment]
closed in favour of #1353

**Pull request closed without merging**
