### PR TITLE
Call onFailure when removing queued publish messages

### LINKED ISSUE #1542: Call onFailure when removing queued publish messages
Why is the onFailure not executed when removing old messages? Not doing so causes memory leakage in paho.mqtt.cpp, as it doesn't release the token in time.

https://github.com/eclipse-paho/paho.mqtt.cpp/issues/525

image

### PR DESCRIPTION
**Pull request by ydddx**
Call onFailure when removing queued publish messages

#1542 
Signed-off-by: ydddx <ydddx@outlook.com>

### CODE REVIEW

**Comment by icraggs** [comment]
Have you been able to test this?

**Comment by icraggs** [comment]
I mean, it looks ok, I wondered if you'd verified it?

**Review by icraggs — APPROVED** [review]

**Comment by icraggs** [comment]
It's ok, I've added a test for this, and merged this commit into the develop and 1.4 branches (https://github.com/eclipse-paho/paho.mqtt.c/commit/cb4facf000ecbc6becc8b301aaf106a23edbfdfd).

Thanks.

**Comment by ydddx** [comment]
I tested this, and it works great.

**Pull request closed without merging**
