### PR TITLE
message token

### PR DESCRIPTION
**Pull request by lun0144**
change some code for message token can use for message ID.

### CODE REVIEW

**Comment by icraggs** [comment]
I don't think this is correct.  It causes tests to fail.  The message id token is returned to the application in the response structure.

**Comment by lun0144** [comment]
But according to my test，If do not modify it,the return message token will not be correct.

**Comment by icraggs** [comment]
The message id is assigned by the client library, and returned to the application.  It's not up to the application to assign it.

**Comment by lun0144** [comment]
ok, thank you .

**Pull request closed without merging**
