### PR TITLE
Add support for TLS-PSK

### PR DESCRIPTION
**Pull request by janderholm**
This change adds support for TLS-PSK. It is done by exposing the OpenSSL callback almost directly to the client so that they may use the _hint_ configured by the server if wanted. It supports registering a application specific context pointer to the callback.

I have also implemented a simple callback to one of the sample apps. Please tell me if I should add it to the others as well.

The sample application have been tested with mosquitto 1.4.14 configured with `psk_file` and `psk_hint`. Note that it is important to specify `psk_hint` or mosquitto will ignore TLS-PSK.

Solves  #146

### CODE REVIEW

**Comment by janderholm** [comment]
I have now signed the ECA. But I don't know how to rerun the checks?

**Comment by icraggs** [comment]
Thanks. If you add another commit, then I think the checks will be re-run.  The CI tests have failed on the TLS tests, so I expect something in your changes is causing those to fail.

**Comment by janderholm** [comment]
I have added two tests for PSK. They work fine locally, but not on Travis. I think this is because Travis does not use mosquitto.conf from this package so I made a pull request here:
https://github.com/eclipse/paho.mqtt.testing/pull/57

**Comment by janderholm** [comment]
I have updated the reviews to include the ability to disable loading of the openssl default certs. The reason is when doing PSK mutual authentication it is probably best to not accept any other brokers even though they may have properly signed certificates.

**Comment by icraggs** [comment]
The tests don't work on Travis because the CI tests there are using the Paho test broker rather than Mosquitto.  I've started looking at adding PSK support to that broker, but in the meantime I'll probably just disable the PSK tests.

**Pull request merged**
