### PR TITLE
Building Deb Package with Debuild

### PR DESCRIPTION
**Pull request by leon-anavi**
This GitHub PR adds configuration files to generate libpahomqttc deb package using Debuild, for example:
```
git clone -b debuild https://github.com/eclipse/paho.mqtt.c.git
mv paho.mqtt.c libpahomqttc-1.0.0
cd libpahomqttc-1.0.0/
debuild -us -uc
```
I don't know if it makes any sense to merge this change in master. I needed a deb file for a hobby project and I just decided to contribute back what I did. Feel free to close the GitHub PR if it is not appropriate or please advise if any improvements are needed to get it merged.

Best regards, Leon

### CODE REVIEW

**Comment by icraggs** [comment]
@jumoog I checked that @leon-anavi has signed the ECA, and it seems that he has.  The IP check must have run before that, so it looks like I can merge this PR.  Obviously I'd like to try it out first :-)

**Comment by miks** [comment]
I just checked against master and it's not building with `debuild -us -uc`.
I guess something has been changed in Makefile.

**Comment by leon-anavi** [comment]
Hi @miks, 

First of all, thank you reviving this old GitHub PR. 

It has been more than a year since I opened it. I don't remember the details. I also need to have a look again and update it but I am not sure if it is worth the efforts if it is going to stay not reviewed/merged for another year or so :) 

Thanks, Leon

**Comment by icraggs** [comment]
I will try it and see what I can figure out.   I wanted to have a way of building a .deb package anyway.

**Comment by miks** [comment]
I have some modifications already to get it working. I'm just curious how can I make back those changes to this pull request.

**Comment by leon-anavi** [comment]
@miks, I guess you can fork https://github.com/AnaviTechnology/paho.mqtt.c make GitHub PR with your changes to branch debuild. After that I will merge them in my fork and they should appear in this GitHub PR :)

Thanks, Leon

**Comment by leon-anavi** [comment]
Hi @miks, @icraggs,

I had a quick look and I fixed the .deb generation on Ubuntu 16.04 with a couple of fixes:
* Downgrade the requirement for debhelper version to 9.2 in debian/control
* Skip MQTTVersion if it does not exist in debian/rules

@icraggs is build/output/MQTTVersion completely gone?

Best regards, Leon

**Comment by miks** [comment]
@leon-anavi: I think `MQTTVersion ` has been renamed to `paho_c_version`.
I have following changes in my `debian/rules` file:
```
        install -D -m 644 build/output/libpaho-mqtt3cs.so.1.0 $$(pwd)/debian/libpahomqttc/usr/local/lib
        install -D -m 644 build/output/libpaho-mqtt3a.so.1.0 $$(pwd)/debian/libpahomqttc/usr/local/lib
        install -D -m 644 build/output/libpaho-mqtt3as.so.1.0 $$(pwd)/debian/libpahomqttc/usr/local/lib
-       install -D build/output/MQTTVersion $$(pwd)/debian/libpahomqttc/usr/local/bin/MQTTVersion
+       install -D build/output/paho_c_version $$(pwd)/debian/libpahomqttc/usr/local/bin/paho_c_version
        install -D -m 644 src/MQTTAsync.h $$(pwd)/debian/libpahomqttc/usr/local/include
        install -D -m 644 src/MQTTClient.h $$(pwd)/debian/libpahomqttc/usr/local/include
        install -D -m 644 src/MQTTClientPersistence.h $$(pwd)/debian/libpahomqttc/usr/local/include
+       install -D -m 644 src/MQTTProperties.h $$(pwd)/debian/libpahomqttc/usr/local/include
+       install -D -m 644 src/MQTTReasonCodes.h $$(pwd)/debian/libpahomqttc/usr/local/include
+       install -D -m 644 src/MQTTSubscribeOpts.h $$(pwd)/debian/libpahomqttc/usr/local/include
```
Extra headers was needed for libpahomqttcpp to build.

**Comment by icraggs** [comment]
Thanks @leon-anavi.

Yes, I changed the name of MQTTVersion to be more general, and to match the utilities paho_c_sub and paho_c_pub, which are now quite functional.   Would it be appropriate to include those as well?   

The utilities also have man pages, as does the API.  I don't know the convention about these and .deb files.

**Comment by leon-anavi** [comment]
Hi @icraggs, @miks,

I have rebased on top of current master. I added patches to set minimal debhelper version compatible with Ubuntu 16.04, updated the list of installed files, added libssl-dev as a build dependency and updated the package version to 1.3.0.

@miks, I have added you in "Co-authored-by:" in the git commit message that updates the list of the installed files according to the latest changes in master of paho.mqtt.c. Thank you for the help on this!

The steps to build the package are:
```
git clone -b debuild https://github.com/AnaviTechnology/paho.mqtt.c libpahomqttc-1.3.0
cd libpahomqttc-1.3.0
make
debuild -us -uc
```
Note: If merged the same steps can be used with the URL to the upstream

To test the package:
```
sudo dpkg -i ../libpahomqttc_1.3.0_armhf.deb
```

I have tested in on Raspberry Pi with Raspbian and x86-64 with Ubuntu 16.04.

@icraggs, could you please review and merge (if there are no remarks) this GitHub PR? I know that this deb package isn't perfect but it better than nothing and it is a good start. I am doing this as a hobby project in my spare time so honestly it is unpleasant to see a GitHub PR staying for more than a year not merged and without any feedback :)

Best regards,
Leon

**Comment by icraggs** [comment]
@leon-anavi Thank you very much, I will try it out tomorrow when I have access to my Ubuntu machine.  Having a starting point will be very useful.  

(I am sorry about the delay - unfortunately my work is spread across quite a few projects, so keeping up with all the requests could be a full time job in itself.   I appreciate you following up on this PR, and I'll try and address the outstanding PR backlog.)

**Comment by icraggs** [comment]
I got (end of the output from debuild):

ln -s libpaho-mqtt3as.so.1.0  build/output/libpaho-mqtt3as.so.1
ln -s libpaho-mqtt3as.so.1 build/output/libpaho-mqtt3as.so
make[1]: Leaving directory '/home/icraggs/git/paho.mqtt.c'
dh_auto_build: make -j8 -O returned exit code 2
debian/rules:4: recipe for target 'binary' failed
make: *** [binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui failed

I'm happy to merge these changes anyway, to get things started.   Just wondering what is happening.  There were some warnings about TLS 1.1.0 which I should fix soon, but I don't think those affected the result.

**Comment by miks** [comment]
@icraggs try compilation by forcing to use only single CPU with `debuild -us -uc -j1`
Looks like debuild by default detect and use multiple system cores whereas paho doesn't support parallel compiling.

**Comment by icraggs** [comment]
Ok, I tried with the command debuild -us -uc -j1 and that seemed not to complain, mostly.  I didn't get a .deb package though, I assume because this was an Intel machine?

I'm happy to merge, but I don't know how much effort it will take to make everything work.

**Comment by icraggs** [comment]
This has been merged into the develop branch.  Thanks.

**Comment by klaussnd** [comment]
This conflicts with the previous existing way of generating a Debian package with `cpack`. After merging this into develop, the Debian package creation with `cpack` is broken.
I think we should decide for one way to generate such packages and stick to it, rather than having two conflicting variants. Since `cpack` is more general (it can also create other types of packages, not only Debian), I would consider `cpack` a better choice. We can also amend the `cpack` configuration to suit the use case of @leon-anavi.

**Comment by leon-anavi** [comment]
Hi @klaussnd,

It has been two years since I created this GitHub PR. Back then I needed the deb file for a hobby project. Nowadays I don't have a particular use case so I don't mind any solution for creating a deb file.

Best regards,
Leon

**Pull request closed without merging**
