### PR TITLE
Fix crash in MQTTClient_cycle when MQTTClient_destroy executed during MQTTClient_run 

### PR DESCRIPTION
**Pull request by michalkas**
The crash happens when during execution of MQTTClient_run method, just before 
MQTTClient_cycle (which is not protected by the mutex) MQTTClient_destroy method is triggered.
It will crash inside MQTTClient_cycle.

Signed-off-by: Michal Kasperek <michalkasperek@gmail.com>

### CODE REVIEW

**Comment by icraggs** [comment]
Is to fix the same issue as #675?  As is stands, it causes multiple tests (mostly concerning connection lost) to fail.

**Comment by michalkas** [comment]
Yes, it is the same issue. Just didn't know how to abandon that pull request. 
I've noticed that this fix is not sufficient, it makes PAHO mqtt to work really slow.

We've came up with another solution. I will propose it next week when I'm back from holidays.

**Comment by icraggs** [comment]
You need to be careful when calling destroy, that the client has actually been disconnected properly.  A trace of the situation (as described in the readme) could help diagnose.

**Comment by michalkas** [comment]
I will add the trace next week if it helps to diagnose it better. 
More detailed issue description is below:
The crash happens even though we are not connected. We are starting the application which tries to connect and we are closing it immediately afterwards. In this case we are not connected yet.
If it happens that during execution of the MQTTClient_run just after unlocking mqttclient_mutex the MQTTClient_destroy method is called the MQTTClient_cycle will work on released resources which causes the app to crash.

**Comment by icraggs** [comment]
It sounds like a simple test program will do the job then - that would be ideal as it can be added to the CI tests.

**Comment by j8phi** [comment]
I think I'm having the same issue. Did you resolve it or working on a new fix?

**Pull request closed without merging**
