### PR TITLE
Visual studio 2013 support

### PR DESCRIPTION
**Pull request by dontsovcmc**
https://github.com/eclipse/paho.mqtt.c/issues/348
For Visual Studio less than 2015.

### CODE REVIEW

**Comment by JuergenKosel** [comment]
This patch is not necessary, because you could generate visual studio files with cmake for any version you like.

**Comment by dontsovcmc** [comment]
There is a problem with "errno.h" file in VS2013 
"Socket.h" includes before "errno.h",  constants became wrong :( -> socket doesn't works

**Comment by icraggs** [comment]
#367 should fix this problem

**Comment by dontsovcmc** [comment]
yes. I close this.

**Pull request closed without merging**
