### PR TITLE
fix(odr): Fix ODR violation for libuuid symbols

### LINKED ISSUE #1319: The LIBUUID macro does not allow you to build a library
I need to build a library with a macro because I get an error when building my code

```
./paho.mqtt.c/build/src/libpaho-mqtt3a.a(WebSocket.c.o): In function `uuid_generate':
WebSocket.c:(.text+0x11): multiple definition of `uuid_generate'
./util-linux/libuuid/src/libuuid_la-gen_uuid.o:/root/utils/util-linux/libuuid/src/gen_uuid.c:551: first defined here
./paho.mqtt.c/build/src/libpaho-mqtt3a.a(WebSocket.c.o): In function `uuid_unparse':
WebSocket.c:(.text+0xc0): multiple definition of `uuid_unparse'
./util-linux/libuuid/src/libuuid_la-unparse.o:/root/utils/util-linux/libuuid/src/unparse.c:74: first defined here
collect2: error: ld returned 1 exit status

```
If I configure the library like this, then the error when making
cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_WITH_SSL=TRUE -DCMAKE_C_FLAGS=-DLIBUUID

```
[ 60%] Linking C executable test_connect_destroy
../src/libpaho-mqtt3c.a(WebSocket.c.o): In function `WebSocket_connect':
WebSocket.c:(.text+0x5cc): undefined reference to `uuid_generate'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_sync_session_present-static.dir/build.make:95: recipe for target 'test/test_sync_session_present-static' failed
make[2]: *** [test/test_sync_session_present-static] Error 1
CMakeFiles/Makefile2:842: recipe for target 'test/CMakeFiles/test_sync_session_present-static.dir/all' failed
make[1]: *** [test/CMakeFiles/test_sync_session_present-static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 61%] Building C object src/CMakeFiles/paho-mqtt3as-static.dir/SSLSocket.c.o
../src/libpaho-mqtt3c.so.1.3.12: undefined reference to `uuid_generate'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_connect_destroy.dir/build.make:95: recipe for target 'test/test_connect_destroy' failed
make[2]: *** [test/test_connect_destroy] Error 1
CMakeFiles/Makefile2:990: recipe for target 'test/CMakeFiles/test_connect_destroy.dir/all' failed
make[1]: *** [test/CMakeFiles/test_connect_destroy.dir/all] Error 2
[ 61%] Linking C static library libpaho-mqtt3a.a
[ 61%] Linking C static library libpaho-mqtt3as.a
[ 61%] Built target paho-mqtt3a-static
[ 61%] Built target paho-mqtt3as-static
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

```

### PR DESCRIPTION
**Pull request by tripleslash**
Fixes #1319

### CODE REVIEW

**Comment by tripleslash** [comment]
@icraggs Do you have any idea why the tests could be failing? I did not touch anything related to OpenSSL

**Comment by icraggs** [comment]
The TLS tests are failing apparently because the test certificates expired at the end of February! I'm sure that seemed a long time in the future when I created them. I'll fix them up.

**Comment by tripleslash** [comment]
Any chance this can get merged? Right now we rely on patch files to build a custom fixed version of paho. If this was approved I could drop the workaround :)

**Comment by tripleslash** [comment]
Any updates? @icraggs

**Comment by kelteseth** [comment]
We are facing the same issue, thanks for the fix @tripleslash . Any updates @icraggs 

I just noticed that this patch is already in use in vcpkg but it does not work for me https://github.com/microsoft/vcpkg/blob/d1badc3307b836866e9009d3e802bf5b181820a7/ports/paho-mqtt/fix-ODR-libuuid-linux.patch

**Comment by icraggs** [comment]
I've merged this into develop. I've changed the default back to FALSE to maintain backward compatibility, and had to add the uuid library if the PAHO_WITH_LIBUUID is set to get it to build on Linux.

**Pull request closed without merging**
